import Header from '@/components/layout/header/header';
import TransitionWrapper from '@/components/layout/transitionWrapper/transitionWrapper';
import type { Metadata } from 'next';
import { ViewTransitions } from 'next-view-transitions-gabriel-azv';
import { Geist, Geist_Mono, Libre_Baskerville, Sen } from 'next/font/google';
import './globals.css';

const geistSans = Geist({
	variable: '--font-geist-sans',
	subsets: ['latin'],
});

const baskerfille = Libre_Baskerville({
	variable: '--font-libre_baskerville',
	subsets: ['latin'],
	weight: ['400'], // Add the desired weights as needed
});

const sen = Sen({
	variable: '--font-sen',
	subsets: ['latin'],
});

const geistMono = Geist_Mono({
	variable: '--font-geist-mono',
	subsets: ['latin'],
});

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<ViewTransitions>
			<html lang='pt-BR'>
				<body
					className={`${geistSans.variable} ${geistMono.variable} ${sen.variable} ${baskerfille.variable} antialiased`}
				>
					<TransitionWrapper>
						<Header />

						{children}
					</TransitionWrapper>
				</body>
			</html>
		</ViewTransitions>
	);
}
